### ISSUE TITLE
QC3 on bam - error on IonTorrent exome sequencing

### ISSUE THREAD

**Issue by tdelhomme** [slzhao/QC3#6]
Hi Shilin,

Very interesting tool with usefull applications!
I am trying to run QC3 on a group of 2 bam files from IonTorrent (TP53 sequencing, single end, aligned with tmap.)
This is the corresponding command line:

```
perl ~/Documents/GitHub_repos/QC3/qc3.pl -m b -i bamTestList -o test_qc3 -r ~/Documents/Models/regressions/somatic_regressions_CIRC/BAMSurgeon/Patrice_LUSC_ctDNA_controls/Bedfile_LUSC_TP53_Exon2_11_200614_sm.bed -t 6
```

And this is the output I get:

```
[Mon May  9 10:00:22 2016] Start bam summary for bamTestList
[Mon May  9 10:00:23 2016] Load target region file '/home/delhommet/Documents/Models/regressions/somatic_regressions_CIRC/BAMSurgeon/Patrice_LUSC_ctDNA_controls/Bedfile_LUSC_TP53_Exon2_11_200614_sm.bed'
[Mon May  9 10:00:23 2016] No gtf file
[Mon May  9 10:00:23 2016] Read bam file and write out
[Mon May  9 10:00:23 2016] Thread 1 started
[Mon May  9 10:00:23 2016] Thread 1 processing /home/delhommet/Documents/Models/regressions/somatic_regressions_CIRC/BAMSurgeon/Patrice_LUSC_ctDNA_mutated/BAM/MLT00BUU.bam
[Mon May  9 10:00:23 2016] Thread 2 started
[Mon May  9 10:00:23 2016] Thread 2 processing /home/delhommet/Documents/Models/regressions/somatic_regressions_CIRC/BAMSurgeon/Patrice_LUSC_ctDNA_mutated/BAM/MLT00BUY.bam
[Mon May  9 10:00:24 2016] Thread 3 started
[Mon May  9 10:00:24 2016] Thread 4 started
[Mon May  9 10:00:24 2016] Thread 5 started
[Mon May  9 10:00:25 2016] Thread 6 started
Use of uninitialized value in join or string at /home/delhommet/Documents/GitHub_repos/QC3/source/bamSummary.pm line 715.
[Mon May  9 10:00:26 2016] Thread 1 finished
Use of uninitialized value in join or string at /home/delhommet/Documents/GitHub_repos/QC3/source/bamSummary.pm line 715.
[Mon May  9 10:00:29 2016] Thread 2 finished
[Mon May  9 10:00:29 2016] Thread 3 finished
[Mon May  9 10:00:29 2016] Thread 4 finished
[Mon May  9 10:00:29 2016] Thread 5 finished
[Mon May  9 10:00:29 2016] Thread 6 finished
[Mon May  9 10:00:30 2016] Finish bam summary!
[Mon May  9 10:00:30 2016] Something wrong in plotting figure. Please check the bamSummary.rLog file!
HTML::Template::param() : attempt to set parameter 'figureloop1' with a scalar - parameter is not a TMPL_VAR! at /home/delhommet/Documents/GitHub_repos/QC3/source/makeReport.pm line 70.
```

associated to this `bamSummary.rLog` file:

```
Error in kruskal.test.default(rawData[, x], rawData[, y]) : 
  all observations are in the same group
Calls: plot_dataFrame -> kruskal.test -> kruskal.test.default
Execution halted
```

I think the problem is when you recover the `lane` for a bam:
This is the first line of one of my bams without the header:

```
1SJ61:08208:09540   16  chr1    1333369 55  11S62M  *   0   0   TGAAGTCTCATGGAAGCCAGCCCCAGCGCGACCCGCCACAGCGCACTGTCCTCACTGGAGCCCCTGCCCTTCC   :;7<<=<<<<=9=9=>9?>>7>><<<==<<<8>=>9888=<<;<;<?=<8<<;=>>9A<808889<7?<9<7<   ZP:B:f,0.00833928,0.00465518,3.077e-06  ZA:i:73 ZG:i:147    ZB:i:30 ZC:B:i,147,147,1,0  ZM:B:s,262,-28,246,4,-2,258,30,274,14,212,0,230,254,0,4,26,240,242,526,-46,498,288,184,214,242,494,6,458,-18,4,736,272,-6,232,-18,1026,8,6,198,14,252,474,2,4,244,276,22,18,242,28,318,188,2,24,428,222,16,32,12,30,240,242,250,18,186,0,0,300,0,-22,198,272,48,236,244,254,-18,4,32,34,168,-20,510,2,32,218,696,6,244,-2,22,-8,196,32,310,254,14,-22,-32,288,8,12,220,98,192,70,4,988,-4,-2,244,52,240,4,470,10,10,220,12,-22,446,10,2,10,446,250,2,4,286,-8,46,292,28,206,-26,238,24,6,-30,44,270,44,262,22,418,278,38,398,300,244,0,202,58,2,0,36,496,62,232,46,92,212,212   ZF:i:25 RG:Z:1SJ61.IonXpress_074    PG:Z:tmap   MD:Z:60A1   NM:i:1  AS:i:58 XM:i:62 XA:Z:map4-1 XS:i:19
```

The first field contains only three arguments (`instrument`, `runNumber`, `flowcell`) and so `lane` will be `NA` and this is not managed by your R script `rFunctions.R`, am I right?

Thanks in advance!

**Comment by slzhao** [comment]
Hello Tiffany,

Would you please try to set "-t 2" and do it again as we have more threads
than tasks here? I will add some code to do a check to avoid it.
Thanks!

Best,
Shilin

2016-05-09 3:17 GMT-05:00 Tiffany Delhomme notifications@github.com:

**Comment by tdelhomme** [comment]
This does not solve the issue...
I do think the problem is the format of my bam, as mentionned it does not contain every information needed in your R script (particularly the `lane` info). I will try to avoid the issue by an option: if the user know that the bam does not contain information about the batch (`instrument`, `runNumber`, `flowcell`) we pass this step. Does it sound good?

Thanks!

Tiffany

**Comment by tdelhomme** [comment]
Hi,

I've added a commit just [here](https://github.com/IARCbioinfo/QC3/commit/2f47a9dee48fa51fed9d808382279745aa862d51) for dealing with non-Illumina data without crashing. This add the option `-no_batch`which remove all the plotting steps for batch effect.
Everything works well now!

**Comment by tdelhomme** [comment]
In case you would like to add some new features like the previous one in your code, let me know and I would submit a pull request.
We can close the issue now!

Best,

Tiffany

**Comment by slzhao** [comment]
Hello Tiffany,

Thanks for your contribution! It greatly improved the package!

Best,
Shilin

2016-05-13 8:58 GMT-05:00 Tiffany Delhomme notifications@github.com:
